[package]
name = "usercall-extension-runner"
version = "0.1.0"
authors = ["Fortanix, Inc."]
license = "MPL-2.0"
edition = "2018"

[dependencies]
aesm-client = { version = "0.5.0", features = ["sgxs"], path="../../../intel-sgx/aesm-client"}
enclave-runner = { version = "0.5.0", path="../../../intel-sgx/enclave-runner"}
sgxs-loaders = { version = "0.3.0",   path="../../../intel-sgx/sgxs-loaders"}
futures = "0.3"
tokio = { version = "0.2", features = ["process"] }
pin-utils = "0.1"
